# -*- coding: utf-8 -*-
# 进阶实例：每个条目形如 (类别, 专有名称, 说明正文, 来源URL)
# 类别取自：工业 / 科研装置 / 医疗 / 能源 / 航天与卫星 / 基础设施
#           / 消费产品 / 气象与海洋 / 国防与安全 / 计量基准 / 通信

ADVANCED = {
    "microwave": [
        ("科研装置", "法国 ITER 电子回旋共振加热系统", "ITER 是法国在建的核聚变装置。它用和家用微波炉同款思路去加热等离子体里的电子，只不过把频率提到毫米波、功率放大几万倍，正好踩在电子自转的频率上把能量一点点喂进去。这套系统顶得上几万台家用微波炉一起开。", "https://www.iter.org/fr/node/16222"),
        ("科研装置", "中国合肥 EAST 托卡马克 ECRH", "合肥的 EAST 托卡马克是一台人造太阳实验装置。它用 140 GHz 的微波从内部加热等离子体里的电子，再把热量稳稳送进中心区域，帮这台装置维持长时间稳定燃烧。", "https://inis.iaea.org/records/z92jm-cmp75"),
        ("科研装置", "德国 Wendelstein 7-X 仿星器 ECRH", "德国的 Wendelstein 7-X 是一台仿星器。它靠 10 支 1 MW 的微波枪连续发射 140 GHz 电磁波，直接加热里面的电子，是目前世界上功率最大的稳态电子回旋加热装置之一。", "https://www.osti.gov/etdeweb/biblio/20625770"),
        ("科研装置", "中国东莞 CSNS 324 MHz 速调管射频源", "东莞的散裂中子源用 324 MHz 的微波去推质子。射频腔里的交变电场像一只无形大手，一下下把质子束团加速到接近光速，好让它们撞出中子来供科学家研究物质结构。", "https://www.newsgd.com/node_5c070fdd03/eb71311503.shtml"),
        ("工业", "美国 CEM MARS 6 微波消解仪", "美国的 CEM 微波消解仪是实验室的前处理能手。它在密闭罐里用 2.45 GHz 微波加热样品，让极性分子自己摩擦生热，几分钟就把土壤和食品煮到两百多度，省下大半天等待。", "https://pdf.directindustry.fr/pdf-en/cem-corporation/mars-6/99459-654015.html"),
        ("工业", "法国 SAIREM 工业微波回温线", "法国的 SAIREM 用 915 MHz 微波给冻肉回温。这个频率比家用微波炉穿得更深，整块肉从里到外一起热而表面不焦，一小时能处理好几吨，是食品厂的解冻流水线。", "https://www.sairem.com/"),
        ("医疗", "医用微波消融治疗仪", "医用微波消融仪是肿瘤微创治疗的工具。针状天线把 2.45 GHz 微波送进肿瘤组织，让水分子高速摩擦升温到六十度以上把癌细胞烫死，针杆用水冷却，伤口只有一个针眼。", "https://www.accessdata.fda.gov/cdrh_docs/pdf18/K183153.pdf"),
        ("工业", "德国 Püschner 工业微波干燥系统", "德国的 Püschner 专做工业微波干燥。它在真空腔里用 2.45 GHz 微波从内部烘干药粉和水果，温度低、不焦糊，一炉能处理上百公斤热敏物料，是制药和食品厂的节能设备。", "https://pueschner.com/en/products/vacuum-drying-freeze-drying"),
        ("气象与海洋", "中国风云三号微波湿度计", "风云三号是我国的极轨气象卫星。它装着一台微波湿度计，用 183 GHz 附近的频率接收大气自己发出的微波，穿透云层算出全球水汽分布，给台风预报提供全天时数据。", "https://www.ygxb.ac.cn/fra/article/doi/10.11834/jrs.20080226/"),
        ("工业", "深圳摩泰科技 MPCVD 金刚石设备", "深圳摩泰的 MPCVD 设备用微波养钻石。它让 2.45 GHz 微波在真空腔里撞出等离子体，把甲烷拆成碳原子一点点在籽晶上长成金刚石，单台功率能到 6 kW，长出和天然钻石一样的晶体。", "http://www.meltex.cn/pd.jsp?id=8"),
    ],
    "induction-stove": [
        ("工业", "中国潍坊 CONDUCT 钢壳感应熔炼炉", "山东潍坊的 CONDUCT 熔炼炉靠电磁感应炼钢。交流电通过线圈在炉料里感应出涡流，金属自己发热熔化，钢水温度能到 1650℃，是铸造厂里常见的大块头设备。", "https://www.conductfurnace.com/product-energy-saving-steel-shell-induction-melting-furnace.html"),
        ("工业", "中国洛阳鸿腾 10 t 中频感应熔炼炉", "洛阳鸿腾的十吨中频炉专门熔铸铁。线圈里 300 Hz 的中频电流在铁水里感应出涡流，比烧煤炉热效率更高、成分更稳，单炉四十多分钟就能出一大锅滚烫铁水。", "https://lyhtdq.en.made-in-china.com/product/ogrpYWVDsxhH/China-10-Ton-Ultra-High-Power-Medium-Frequency-Induction-Steel-Melting-Furnace-Fume-Extraction-System-for-Steel-Mill-Smelting-Plant.html"),
        ("科研装置", "俄罗斯列别杰夫所冷坩埚壳熔法", "俄罗斯的列别杰夫所用高频感应做冷坩埚。水冷铜模里的高频磁场让物料自己发热，内壁冻出一层冷壳把污染隔开，温度能超过 3000℃，用来长氧化锆晶体和固化核废料。", "https://www.azom.com/article.aspx?ArticleID=20319"),
        ("科研装置", "中国铁岭大型壳熔法设备", "辽宁铁岭的大型壳熔设备用高频感应熔氧化锆。冷坩埚直径做到一米、单炉装料超过一吨，高频磁场让粉末在自家冷壳里融化而不沾坩埚，专做人造宝石和特种晶体。", "https://www.jewellery.org.cn/jewelleryorgwebsite/sub/public_link?label_id=381&page_no=1&element_id=3266&element_type=0"),
        ("工业", "北美 Electroheat 钢壳感应熔炼炉", "北美的 Electroheat 钢壳炉靠感应熔金属。交变磁场在金属里感生涡流发热，不用烧火、升温快、温度好控制，钢铜铝都能熔，是铸造车间回收旧料的主力设备。", "https://electroheatinduction.com/induction-furnace-for-steel-melting"),
        ("工业", "中国江苏宇润 IGBT 中频感应熔炼炉", "江苏宇润的 IGBT 中频炉更省电。电磁感应直接加热炉料，比老式可控硅炉省一成多电费，功率从十万瓦到三百万瓦都能做，已服务几十个国家的铸造厂。", "http://yrmfpower.com/"),
        ("工业", "加拿大 AMELT 钢架感应熔炼炉", "加拿大的 AMELT 钢架炉专做大批量熔炼。中频涡流让金属内部自己发热，取代冲天炉，灰尘和废气都更少，一小时能熔一两吨，适合钢铁和有色铸造车间。", "https://www.amelt.com/steelframe"),
        ("工业", "美国 Inductotherm 感应熔炼系统", "美国的 Inductotherm 做了六十年感应熔炼设备。它给铸造厂造无芯感应炉，交变磁场在金属里感生涡流直接熔化，全世界已装了四万多套，从几公斤到几十吨都能干。", "https://www.inductotherm.com/investment-casting/"),
        ("能源", "WiTricity 无线充电（电动汽车）", "WiTricity 让电动车停上去就充电。地面线圈和车底线圈调到同一频率，靠磁场共振隔空把电送进电池，对准要求很松，效率能到九成免去插拔电缆的麻烦。", "https://www.witricity.com/products/automotive/"),
        ("工业", "美国 Enercon 电磁感应封口机", "Enercon 的封口机给瓶盖焊铝箔。感应线圈在瓶盖下产生磁场，让内垫里的铝箔发热熔化胶层，粘住瓶口，液体不漏还能防伪，超市里酱料瓶的封膜就是它做的。", "https://www.enerconind.com/sealing/library-resource/liner-options-for-sealing-containers"),
    ],
    "pressure-cooker": [
        ("工业", "中国 LUY 工业复合/食品蒸压釜", "LUY 的工业蒸压釜是个大压力容器。密封罐里通蒸汽加压，把水的沸点抬到一百多度以上，食品灭菌和复合材料固化都在这种均匀温压里完成，一年能造几千台。", "https://www.woodtreatmentplant.com/sale-53139127-sports-field-high-temperature-and-pressure-resistant-material-composite-autoclave.html"),
        ("航天与卫星", "中国航空工业 φ7 m×30 m 大型热压罐", "航空工业的大型热压罐专做飞机翅膀。罐内用压缩空气压到两三个大气压、加温到一百二十到一百八十度，把真空袋里的碳纤维预浸料压牢固化，造出又轻又硬的大构件。", "https://www.aibangfrp.com/a/8581"),
        ("工业", "Olymspan 航空级复合热压罐", "Olymspan 的航空级热压罐做复材构件。密封罐里用热空气均匀加压到一点三大气压、保持一百五十度，逼出树脂里的气泡，让碳纤维层合板更密实，用在飞机和汽车上。", "https://ar.htnxt.com/page/Composite-Autoclave-Systems:-Core-Technology-and-Industrial-Applications-Guide.html"),
        ("航天与卫星", "德国 SCHOLZ 大型热压罐", "德国的 SCHOLZ 几十年卖了五百多台热压罐。最大的罐有六十米长，用蒸汽加压让树脂在真空袋里交联固化，是造大飞机复材构件的核心装备，空客波音都用它。", "https://www.aibangfrp.com/a/8581"),
        ("科研装置", "意大利 Terruzzi 热压罐", "意大利的 Terruzzi 给火箭和飞机供热压罐。密封罐里抽真空再通压缩空气加压加热，让环氧树脂流动交联，造出轻而强的航空结构件，已交付六百多套。", "https://www.aibangfrp.com/a/8581"),
        ("医疗", "医用高压灭菌器", "医院里的高压灭菌器靠蒸汽杀菌。密闭耐压罐里饱和蒸汽压到约零点一大气压、升到 121℃，维持二十多分钟，连细菌芽孢都烫死，是器械消毒的标准办法。", ""),
        ("工业", "中国 SINOMAC 超高温高压热压罐", "SINOMAC 的超高温热压罐做战略复材。密封罐里通氮气加压到五大气压、加温到三百多度，固化耐高温树脂，用来造火箭整流罩和卫星筒段这些大尺寸构件。", "http://en.czsinomac.com/list_11.html"),
        ("工业", "食品工业高压杀菌釜", "食品厂的高压杀菌釜给罐头灭菌。密闭罐里饱和蒸汽压高于常压，沸点升高，把中心温度升到 121℃ 保持几十分钟，灭掉肉毒杆菌，让罐头放很久不坏。", "https://www.endlesswiki.com/wiki/autoclave-processing"),
        ("能源", "上海电气 超超临界燃煤锅炉", "上海电气的超超临界锅炉烧煤发电。炉膛里蒸汽压力压到 25 MPa 以上、温度超过 600℃，水几乎贴着临界点在流动，高温高压让煤烧得更省、电发得更多。", "https://shanghaielectric-smec.com/1-4-3-600mw-thermal-power-plant-boiler/"),
        ("科研装置", "中国铰链式六面顶压机", "六面顶压机是造人造钻石的机器。六个液压锤从四面八方把石墨压到几万大气压、加热到一千三百度以上，石墨就变成金刚石，我国九成以上的人造钻石靠它量产。", "https://baike.baidu.com/item/%E8%B6%85%E7%A1%AC%E6%9D%90%E6%96%99%E5%85%AD%E9%9D%A2%E9%A1%B6%E6%B6%B2%E5%8E%8B%E6%9C%BA/55708094"),
        ("能源", "红沿河核电站反应堆压力容器", "核电站的反应堆压力容器是装核燃料的钢罐。它在 155 个大气压、三百多度高温下关着裂变反应，壁厚两三百毫米、重两三百吨，六十年不让换，是电站的心脏。", "https://www.chinanews.com.cn/ny/2018/12-03/8691221.shtml"),
    ],
    "thermos": [
        ("能源", "中国海油 CGTank 27 万 m³ LNG 储罐", "中国海油的 LNG 储罐是个巨无霸。单罐能装 27 万立方米零下 162 度的液化天然气，罐壁夹层抽真空又填保温棉，把每天蒸发掉的量压到极小，守住能源储备。", "http://www.sasac.gov.cn/n2588025/n2588124/c35053911/content.html"),
        ("能源", "中国石化天津 LNG 接收站", "天津的 LNG 接收站是华北的天然气枢纽。好几座 22 万立方米储罐双壁全容、夹层真空绝热，外罐挡泄漏、内罐存零下 162 度天然气，调峰供气全靠它。", "https://www.gem.wiki/Tianjin_LNG_Terminal_%28Sinopec%29"),
        ("科研装置", "CERN LHC 超流氦低温系统", "欧洲大型强子对撞机的磁体泡在超流氦里。近两万吨设备用真空夹层杜瓦裹住，靠 1.9 K 的液氦导热把超导磁体稳在极低温，才能产生八特斯拉以上的强磁场。", "https://cern-courier.web.cern.ch/a/how-cern-keeps-its-cool/"),
        ("医疗", "医用 MRI 超导磁体液氦杜瓦", "医院里的 MRI 靠液氦杜瓦镇住强磁场。超导线圈泡在 4.2 K 液氦里，杜瓦是双层真空夹层，每年只蒸发不到零点一升，让磁共振成像稳定又省钱。", ""),
        ("工业", "中国无锡 Triumph 真空绝热低温储罐", "无锡 Triumph 的低温储罐存深冷液体。双壁真空夹套配多层绝热，能扛零下 196 度，日蒸发率不到千分之五，LNG 和液氦这些低温液体靠它长途储运。", "http://www.cryotriumph.com/Cryogenic-Liquid-Storage-Tank-pd581291158.html"),
        ("工业", "食品生物冷链真空绝热储罐", "食品和生物制品的冷链罐容量从半方到十方，也靠真空绝热。不锈钢罐夹层抽真空加反射屏挡住漏热，日蒸发不到千分之三，比普通泡沫箱少蒸七成，疫苗和冰淇淋基料的中短途冷藏全靠它。", "https://gasequipment.ltd/product/lng-cryogenic-storage-tanks-high-capacity-fast-delivery"),
        ("基础设施", "低温液体公路罐车", "拉深冷液体的公路罐车是杜瓦型，罐容二十到五十方。内胆和外罐之间高真空多层绝热，运输零下 196 度液体时蒸发极小，工业气体和清洁能源的配送全靠它在路上跑。", "https://gasequipment.ltd/product/lng-cryogenic-storage-tanks-high-capacity-fast-delivery"),
        ("航天与卫星", "航天低温载荷液氦/液氮杜瓦", "空间望远镜的探测器泡在深冷杜瓦里，工作温区四到八十开。杜瓦用三五十层绝热加高真空，液氦液氮慢慢蒸发吸热，把探测器降到近红外本底所需的低温，是航天热控关键件。", ""),
        ("基础设施", "真空绝热板（VIP）建筑与冰箱保温", "真空绝热板是块抽了真空、厚常不到两厘米的夹芯板。芯材外裹阻隔膜封死空气，导热系数只有传统保温材料的十分之一，冰箱贴它能薄壁大肚，建筑外墙也能省下厚度。", "https://www.kepuchina.cn/article/articleinfo?business_type=100&classify=0&ar_id=364501"),
        ("能源", "上海 35 kV 公里级高温超导电缆", "上海的超导电缆泡在液氮里输电。零下 196 度的环境让电缆电阻几乎归零，一根线就能送两千多安培的电流，顶好几根常规电缆，还省下大量地下空间。", "https://sh.people.com.cn/n2/2021/1223/c134768-35065101.html"),
        ("消费产品", "膳魔师真空保温瓶", "膳魔师是做真空保温瓶的老牌子，一九零四年就在柏林起家。双层不锈钢中间抽成真空切断热传导，早上灌的热水到下午还烫嘴，保温杯和焖烧罐都靠这层真空守住温度。", "http://www.thermos.com.cn?brand-index-1.html/"),
    ],
    "fridge": [
        ("基础设施", "中国北京麦德龙立水桥跨临界 CO2 制冷", "北京麦德龙店里用跨临界 CO2 制冷。二氧化碳在超临界状态下循环，用气体冷却器代替冷凝器，这种天然工质不破坏气候，比老制冷剂少漏很多温室气体。", "http://www.carel.in/story-detail/-/asset_publisher/mFz9iSHGzBlI/content/first-metro-transcritical-co2-store-in-china-efficiency-and-reliability-with-carel-retail-sistema/10191"),
        ("基础设施", "中国张北阿里云浸没式液冷数据中心", "张北的阿里云数据中心泡在液体里散热。服务器浸在绝缘冷却液，热量直接被液体带走，不用机械制冷，年均能耗比普通机房低七成，PUE 能到一点零九。", "https://baike.baidu.com/item/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4%E4%BF%A1%E6%81%AF%E7%A7%91%E6%8A%80%EF%BC%88%E5%BC%A0%E5%8C%97%EF%BC%89%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/20619298"),
        ("科研装置", "CERN LHC 低温制冷厂", "欧洲对撞机的低温厂是个大冷库。八座低温岛把氦气一级级液到 1.9 K，总电输入三十多兆瓦，维持二十七公里隧道里的超流氦，撑起整台机器最冷的环节。", "https://cern-courier.web.cern.ch/a/the-challenge-of-keeping-cool"),
        ("工业", "中国理化所/齐耀动力 LNG 船 BOG 再液化", "中科院的 BOG 再液化装置服务 LNG 船。低温制冷机把漏掉的液化天然气蒸气重新冻成液体，省得排到天上又稳住舱压，样机已通过船级社认证准备交付。", "https://cryo.ipc.cas.cn/xwdt/kydt/202504/t20250409_530585.html"),
        ("工业", "中国成都 TCWY BOG 再液化装置", "成都 TCWY 的再液化装置处理蒸发气。它用逆布雷顿氮循环或液氮把 LNG 跑掉的气体重新液化，一天能处理几十到几百吨，接收站和运输船都靠它零排放保冷。", "https://www.maoyt.com/test/tcwygasplant.com/sale-11309779-boil-off-gas-bog-lng-reliquefaction-plant-with-30-to-500-tons-per-day-capacity.html"),
        ("能源", "荷兰 Staay 全球最大 CO2 制冷系统", "荷兰 Staay 的 CO2 制冷系统很能打。总容量三点三六兆瓦，跨临界循环既制冷又回收废热，供蔬菜大棚和加工厂调温，是食品冷链里的能效标杆。", "https://www.mdpi.com/1996-1073/12/15/2959/xml"),
        ("工业", "欧洲商超跨临界 CO2 制冷系统", "欧洲超市铺了四万多套跨临界 CO2 制冷。单店冷负荷一百多千瓦，制冷剂年漏率不到一成，还能回收余热满足门店近六成供暖，是零售业低碳制冷的主流。", "https://www.precisionreports.co/market-reports/transcritical-co2-refrigeration-unit-market-600197"),
        ("科研装置", "稀释制冷机低温系统", "稀释制冷机是超导量子计算的冷源。它先用脉冲管预冷到四度，再靠氦三氦四混合室稀释把温度拉到十毫开，把微观系统逼近绝对零度，量子比特才安静得下来。", ""),
        ("航天与卫星", "JWST 中红外仪低温冷却器", "韦伯望远镜的中红外相机靠一台制冷机降温。氦气在细管里循环把探测器压到 7 K 以下，只比绝对零度高几度，好让它在太空里看清远处星系发出的红外光。", "https://www.nasa.gov/feature/jpl/nasa-s-webb-telescope-will-have-the-coolest-camera-in-space/"),
        ("消费产品", "半导体车载冰箱（美固 Mobicool）", "车载半导体冰箱靠一块制冷片，美固 Mobicool 是其中老牌。电流过两种不同材料结面就把热从一边搬到另一边，没有压缩机、不响，能比环境温度低二十度，自驾露营带饮料正合适。", "http://www.cnscience.com/news/html?106857.html"),
        ("能源", "溴化锂吸收式制冷机（余热制冷）", "溴化锂制冷机不用电压缩机，靠热不直接用电。它用工厂八十度以上的废热水去加热溴化锂溶液，析出的水蒸气在低压下蒸发吸热，把热量从车间搬走，废热变冷气。", "https://baike.baidu.com/item/%E6%BA%B4%E5%8C%96%E9%94%82%E5%90%B8%E6%94%B6%E5%BC%8F%E5%88%B6%E5%86%B7%E6%9C%BA/10976471"),
    ],
}
