# -*- coding: utf-8 -*-
# 高级在役实例：green-laser / loudspeaker / smoke-detector / mri
# 每个条目为 (类别, 专有名称, 说明正文, 来源URL)
# 类别取值：工业 | 科研装置 | 医疗 | 基础设施 | 航天与卫星 | 计量基准 | 消费产品 | 通信 | 能源 | 气象与海洋 | 国防与安全

ADVANCED = {
    "green-laser": [
        ("消费产品", "Barco SP4K-25C 影院激光放映机",
         "Barco的SP4K-25C是影院机房里的激光放映机。它用红绿蓝三束激光合成白光打上银幕，绿色那束被锁在很窄的波长上，所以颜色特别纯。一台能亮到两万四千流明，大影厅也照得透。",
         ""),
        ("科研装置", "MMT 瑞利激光导星系统",
         "美国霍普金斯山的MMT望远镜口径六点五米。它向高空打两束绿色激光，在二十到二十九公里处造出人造星点，帮望远镜校正大气抖动。每束十五瓦，让远处的星星拍得清。",
         ""),
        ("医疗", "Boston Scientific GreenLight XPS 532 nm 激光",
         "GreenLight XPS是一把对付前列腺增生的绿激光刀。它的波长是五百三十二纳米，被血液强吸收，只扎进组织不到一毫米就汽化增生部分。最大一百八十瓦，顺带烫出薄薄一层止血带。",
         ""),
        ("工业", "Coherent AVIA 532-23 工业激光器",
         "Coherent的AVIA532-23是工厂流水线上的绿光打标机。它把红外光在腔内倍频成五百三十二纳米绿光，连续输出二十三瓦。光束很稳，用来在手机零件上刻字、切薄片。",
         ""),
        ("计量基准", "NIST C 系列激光功率量热标准",
         "美国NIST的C系列是给激光功率定尺子的国家标准。它在五百三十二纳米波长上把一微瓦到两瓦的光都称一遍，不确定度约百分之一。别的实验室都拿它当上游基准往上溯源。",
         ""),
        ("工业", "大族激光 PG5 / HL-NS-532 绿光激光器",
         "深圳大族的两款绿光机装在电子珠宝产线上。PG5打出单脉冲四焦耳的绿光，HL-NS-532则做十到四十瓦的纳秒刻蚀。它们把玻璃、硅片表面的标记切得又细又干净。",
         ""),
        ("航天与卫星", "APOLLO 月球激光测距",
         "阿波罗登月时留在月面的角反射器今天还在用。地面用三点五米望远镜打绿光，光跑三十八万公里来回一趟，靠纳秒计时反推地月距离。它至今仍是厘米级精度的空间测地手段。",
         ""),
        ("消费产品", "Kvant Spectrum 20 激光表演投影机",
         "斯洛伐克Kvant的Spectrum20是演唱会头顶的激光秀机器。它总光功率二十瓦，其中绿色通道八瓦，扫描飞快。人眼对绿光最敏感，所以夜空里那道绿束格外扎眼。",
         ""),
        ("医疗", "ZEISS VISULAS green 眼科激光",
         "ZEISS的VISULAS green是眼科医生的眼底激光笔。它发出五百三十二纳米绿光，专烧视网膜上漏血的血管点。最大到角膜一千五百毫瓦，把糖尿病眼底出血焊住不扩散。",
         "https://www.zeiss.com/visulasgreen"),
        ("工业", "Bosch GLL 3-80 CG 绿光水平仪",
         "Bosch的GLL3-80CG是装修师傅手里的绿光水平仪。它吐出三条三百六十度的绿线，在墙上标出横平竖直。绿光比红光显眼约四倍，最远能照到一百二十米。",
         "https://www.bosch-pt.com.cn/cn/zh/products/gll-3-80-cg-0601063U80"),
    ],
    "loudspeaker": [
        ("消费产品", "L-Acoustics K2 线阵列音箱",
         "L-Acoustics的K2是演唱会主力音箱。一箱能吼到一百四十七分贝，从很低到很高都覆盖。多只串成一列时波阵面叠成准柱面波，把声音推到远处也不散。",
         ""),
        ("基础设施", "IMAX 商用影厅六声道扬声器阵",
         "IMAX影厅背后藏着一套六声道加低频的扬声器巨阵。总功率常过一万五千瓦，低频单元一排列开。爆炸声从二十米外的观众席传来，依旧震得人胸口发闷，低频特效藏不住。",
         ""),
        ("国防与安全", "AN/SQS-53C 舰壳主动声呐",
         "美军驱逐舰肚子上贴着AN/SQS-53C声呐阵。五百七十六块陶瓷片把电变成声波灌进海水，声源级约二百三十五分贝。发出去再听回波，就能算出潜艇多远。",
         ""),
        ("科研装置", "Holosonics Audio Spotlight AS-24 参量超声阵",
         "Holosonics的AudioSpotlight是一块会指向的声板。它先发两束高频超声在空气中互撞，差频落成可听声，于是声音只朝一个方向钻。离一米还有八十五分贝。",
         ""),
        ("消费产品", "Sennheiser HE 1 静电耳机",
         "森海塞尔的HE1是发烧友眼里的静电耳机巅峰。它以七百八十伏极化一层两微米多的振膜，失真低到几乎听不出。频响从很低到很高都平，是业界公认的参考级。",
         ""),
        ("基础设施", "锐丰 LAX 国家体育场扩声系统",
         "广州锐丰给北京鸟巢做的扩声系统铺了二百三十六只音箱。全场分二十四个区，九万多座位都要听得清。露天大空间里靠波阵面耦合，把声音均匀拢向观众席。",
         ""),
        ("消费产品", "d&b audiotechnik KSL8 线阵列音箱",
         "d&b的KSL8是大场合用的线阵列音箱。一只最大一百四十五分贝，侧边另藏低频单元做心形指向。这样台后漏气少，乐队自己听返送也干净，场地更安静。",
         "https://www.dbaudio.com/global/en/products/all/series/sl-series/?system=ksl"),
        ("气象与海洋", "ATOC 海洋声学测温声源",
         "美国ATOC在夏威夷外海八百米深处放了低频声源。它哼着七十五赫兹的调子，声功率约二百六十瓦。声波沿深海声道跨太平洋，用快慢反推海水升了几度。",
         "https://www.federalregister.gov/d/01-20647"),
        ("消费产品", "Shokz OpenRun 骨传导耳机",
         "Shokz的OpenRun是跑步者挂在耳朵上的骨传导耳机。它不塞耳朵，而是用振动把声音直接送进颞骨。你既能听歌，又听得见身边的车声和人声，跑步更安全。",
         "https://www.shokz.com/"),
        ("国防与安全", "Federal Signal Modulator 户外警报器",
         "Federal Signal的Modulator是立在杆顶的户外警报阵列。它用一摞喇叭单元朝四面放警报声，最远能传近一公里。龙卷风或化灾来了，它先替城里人喊一嗓子。",
         "https://www.fedsig.com/warning-mass-notification-systems/sirens-speakers/"),
        ("医疗", "Phonak Audéo Lumity 助听器",
         "峰力的Audéo Lumity是塞进耳朵里的助听器。它用蓝牙接管手机声，再用算法把人说话从噪声里拎出来。开会或逛街时，你想听清的那句它都帮你顶上去。",
         "https://www.phonak.com/en-us/hearing-devices/hearing-aids/audeo-lumity."),
    ],
    "smoke-detector": [
        ("工业", "Xtralis VESDA-E VEU 吸气式探测器",
         "Xtralis的VESDA-E VEU是数据中心里主动抽气的探测器。它用管子把空气吸进激光腔，灵敏度高到百分之零点零零几。起火前几小时就先报警，好联动灭火。",
         "https://www.foxvalleyfire.com/wp-content/uploads/2022/06/NOTIFIER-VESDA-E-VEU-Series-Intelligent-Aspiration-Detectors-Data-Sheet.pdf"),
        ("航天与卫星", "波音 787-8 货舱烟雾探测",
         "波音787的货舱里布着光电烟感。前舱十四个、后舱八个，分成两路，要同舱至少两个探测器一起叫才确认火警。双色灯能区分灰尘和真烟，既快又稳，少误报。",
         "https://fliphtml5.com/quwam/hphu/Boeing_B787_Refresher/314"),
        ("基础设施", "1980 年 MGM Grand 酒店火灾与逐室探测",
         "一九八零年拉斯维加斯MGM酒店一把火夺走八十五条命。当时客房里没装烟感，许多人睡着就没逃掉。这场惨剧逼出了内华达州立法，高楼每间房都得装烟感。",
         "https://www.missedhistory.com/article/mgm-grand-fire-las-vegas-1980"),
        ("消费产品", "Kidde P4010ACSCO-WCA 家用光电烟感",
         "Kidde的P4010是家里天花板上的光电烟感。它用发光管和接收管成个钝角，烟一进来就把光打偏触发报警。一百二十伏供电还带十年电池，十英尺外叫到八十五分贝。",
         "https://www.kidde.com/fire-safety/fr/ca/produits/avertisseurs-combines-fumee-co/p4010acsco-wca/"),
        ("工业", "青鸟消防 JBF-AR10P4 吸气式探测器",
         "青鸟消防的JBF-AR10P4是四管主动抽气的探测器。单管打一百个采样孔，保护面积能到四千多平米。高铁站和机房里靠它极早嗅出烟，抢在明火前。",
         "https://baike.jbufa.com/index.php/JBF-AR10P4%E5%90%B8%E6%B0%94%E5%BC%8F%E6%84%9F%E7%83%9F%E7%81%AB%E7%81%BE%E6%8E%A2%E6%B5%8B%E5%99%A8"),
        ("航天与卫星", "空客 A350 货舱烟雾探测",
         "空客A350的货舱顶板凹槽里藏着光电探测器。每个凹槽放两只，要同舱至少两个一起报警才算数。飞机跨洋飞得久，这套冗余让货舱监测更靠谱，也满足远程要求。",
         "https://caucanimax.com/blog/a350-dsc-26-fire-and-smoke-protection/"),
        ("科研装置", "CERN LHC 实验洞室吸气式探测",
         "欧洲核子中心的地下大厅装着吸气式烟感。强子对撞机隧道有辐射，能装机器的位置有限，所以主动抽气覆盖实验区。激光腔辨烟，再联动通风和气体监测保安全。",
         "https://inspirehep.net/files/ebf917f0335d176687a6ccce4b89917c"),
        ("航天与卫星", "国际空间站激光散射式烟感",
         "国际空间站美国舱用激光前向散射的吸气烟感。微重力下没有自然对流，它得主动把气抽进通风回路才看得到全舱。俄罗斯舱也布了十来个，最小能抓零点三微米的颗粒。",
         "https://www.nist.gov/system/files/documents/el/fire_research/R0200471.pdf"),
        ("气象与海洋", "NASA MODIS 卫星火点监测",
         "NASA的Terra和Aqua卫星载着MODIS传感器看火。它专盯四微米和十一微米波段的异常热，一个像元约一平方公里。火一冒头，三小时内就把位置发到消防员的地图上。",
         "https://modis.gsfc.nasa.gov/data/dataprod/mod14.php"),
        ("工业", "Consilium Salwico EV-P 船舶烟感",
         "Consilium的Salwico EV-P是焊在船舱顶上的光电烟感。它按SOLAS规矩装在客船机房和住舱，烟一进就连续上报火控屏。远洋船上震得晃、咸得锈，它都得扛住不误报。",
         "https://www.smmarineservice.com/product-view/782/10"),
        ("消费产品", "Kidde i9070 电离式烟感",
         "Kidde的i9070是家里用电池的电离烟感。它里头一小片放射性源让空气带电，烟一进来就打乱电流触发尖叫。对付烧得猛的明火比光电式更快，九伏电池断电也不瞎。",
         "https://www.kidde.com/products/smoke-alarms/front-load-battery-smoke-alarm"),
    ],
    "mri": [
        ("医疗", "联影 uMR Jupiter 5T 全身磁共振",
         "联影的Jupiter 5T是全球第一台能从头扫到脚的5T临床磁共振，已经装进中山、协和这些大医院。它卡在一个巧点上：场强比常见的3T高，看得更清，又没高到让人体吸收的射频能量超标，所以能安全地用在全身检查。",
         ""),
        ("医疗", "ViewRay MRIdian 磁共振引导放疗",
         "ViewRay的MRIdian把弱磁场磁共振和放疗机拼在一起。零点三五特斯拉的磁场边照边看软组织，肿瘤随呼吸挪了就立刻跟住射线。这样放疗束只咬住癌灶，少伤好肉。",
         "https://www.mdpi.com/resolver?pii=jcm11164730"),
        ("医疗", "Hyperfine Swoop 床旁低场磁共振",
         "Hyperfine的Swoop是能推到病床边的便携磁共振。场强只有零点零六四特斯拉，整机六百三十公斤，不用液氦。危重病人不必搬动，在ICU床头就能照个脑。",
         ""),
        ("医疗", "Elekta Unity MR-linac",
         "Elekta的Unity把一点五特斯拉磁共振和直线加速器合体。它边照边用五帧每秒的电影盯着器官动，射线随时跟着改方向。肝癌随呼吸晃，也能被它咬得很准。",
         "https://pmc.ncbi.nlm.nih.gov/articles/pmid/39165591/"),
        ("医疗", "联影 uMR OMEGA 3T 超大孔径",
         "联影的uMR OMEGA是一台孔径七十五厘米宽的3T磁共振。比常规机器胖出一截，胖人进去做检查不憋屈，偏中心的部位也好摆。中国多家医院在用，还出口到了欧洲。",
         "https://usa.united-imaging.com/products/magnetic-resonance/umr-omega/"),
        ("计量基准", "NIST 磁共振生物标志物计量系统",
         "美国NIST的这套装置是给磁共振量值定标准的。它在零点五到七特斯拉之间标定质子的T1、T2和扩散系数，向上溯源到国际单位。多中心比对着扫，结果才说得准。",
         "https://www.springermedizin.de/metrology-for-mri-the-field-you-ve-never-heard-of/50767158"),
        ("科研装置", "MGH Connectom 300 mT/m 梯度磁共振",
         "麻省总院的Connectom是一台特制3T磁共振。它的梯度强到三百毫特斯拉每米，把编码时间缩得极短，专拍脑白质的细丝。因为太猛只准扫脑袋，全球没几台。",
         "https://pmc.ncbi.nlm.nih.gov/articles/PMC5996223"),
        ("消费产品", "Siemens MAGNETOM Skyra 3T",
         "西门子Skyra是医院里常见的3T磁共振主力。孔径七十厘米，零液氦蒸发，最高两百多接收通道。它把脑心肌骨的扫描流程做得又快又稳，全球每天海量病人在用它。",
         "https://www.siemens-healthineers.com/at/refurbished-systems-medical-imaging-and-therapy/ecoline-refurbished-systems/magnetic-resoncance-imaging-ecoline/magnetom-skyra-eco"),
        ("科研装置", "Siemens MAGNETOM Terra 7T 磁共振",
         "西门子MAGNETOM Terra是首台拿到临床许可的7T磁共振。场强是常规3T的两倍多，信噪比更高，能看出不到一毫米的脑结构。它还能切到科研模式，做代谢成像。",
         "http://www.siemens-healthineers.cn/magnetic-resonance-imaging/7t-mri-scanner/magnetom-terra"),
        ("科研装置", "Bruker BioSpec 7T 动物磁共振",
         "Bruker的BioSpec是给小鼠兔子照的7T动物磁共振。它的孔才二十厘米，梯度却极猛，能把老鼠脑拍到二十五微米见方。新药和脑科学实验里，常拿它看活体细微变化。",
         "https://www.bruker.com/pt/products-and-solutions/preclinical-imaging/mri/biospec.html"),
    ],
}
